// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVaAMKShKp51HBhXxhCQTrWMVo5PYQt0',
    appId: '1:1052300590733:android:7df036cdb2b08477b16cc4',
    messagingSenderId: '1052300590733',
    projectId: 'asn-chat-ca028',
    storageBucket: 'asn-chat-ca028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGDnipNbv7po6DirvtHStJOSVdPrQjkQ',
    appId: '1:1052300590733:ios:1a5aa60a7af8a890b16cc4',
    messagingSenderId: '1052300590733',
    projectId: 'asn-chat-ca028',
    storageBucket: 'asn-chat-ca028.appspot.com',
    androidClientId: '1052300590733-n757ghjcmn582jgo3negtrrgar7k7r77.apps.googleusercontent.com',
    iosClientId: '1052300590733-d4v8pruun7pbv5elkvo36acmsli2g3ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
